# Generated by Django 3.2.4 on 2021-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211129_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/thumbnails'),
            preserve_default=False,
        ),
    ]
