# Generated by Django 4.0.1 on 2022-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='answer/ask_suject')),
            ],
        ),
    ]
