# Generated by Django 4.0.1 on 2022-03-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingChapter',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('class_no', models.IntegerField(default=0, max_length=5)),
                ('ch1', models.CharField(default='', max_length=100)),
                ('ch2', models.CharField(default='', max_length=100)),
                ('ch3', models.CharField(default='', max_length=100)),
                ('ch4', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
