# Generated by Django 4.0.1 on 2022-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0002_trendingchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='For_Class_Subjects',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('class_no', models.IntegerField(default=0)),
                ('subjects', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
