# Generated by Django 4.0.1 on 2022-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0003_for_class_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('chapters_class', models.IntegerField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('names', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question_class', models.IntegerField(default=0)),
                ('subject', models.CharField(default='', max_length=100)),
                ('question', models.CharField(default='', max_length=1000)),
                ('choose1', models.CharField(default='', max_length=100)),
                ('choose2', models.CharField(default='', max_length=100)),
                ('choose3', models.CharField(default='', max_length=100)),
                ('choose4', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
