# Generated by Django 4.0.1 on 2022-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0004_chapter_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
