# Generated by Django 4.0 on 2021-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ref_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=199)),
                ('author', models.CharField(default='', max_length=199)),
                ('content', models.TextField(default='')),
                ('views', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnail')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
