# Generated by Django 4.0 on 2021-12-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_timestamp_alter_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewedBy',
            field=models.TextField(default=''),
        ),
    ]
