# Generated by Django 4.0 on 2021-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_viewedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_story',
            field=models.TextField(default=''),
        ),
    ]
