# Generated by Django 3.2.4 on 2021-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('head0', models.CharField(max_length=500)),
                ('content_head0', models.CharField(max_length=5000)),
                ('head1', models.CharField(max_length=500)),
                ('content_head1', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=500)),
                ('content_head2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
