# Generated by Django 4.0 on 2022-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('sno', models.AutoField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=300)),
                ('singer', models.CharField(default='', max_length=300)),
                ('cover', models.ImageField(upload_to='blog/thumbnail')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
