# Generated by Django 4.0 on 2022-01-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
