# Generated by Django 4.0 on 2022-01-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_song_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
