# Generated by Django 4.0 on 2022-01-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_song_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('sno', models.AutoField(default='', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('singer', models.CharField(default='', max_length=300, null=True)),
                ('cover', models.ImageField(upload_to='blog/thumbnail')),
                ('purchases', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
