# Generated by Django 4.0 on 2022-01-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_album_rename_name_song_title_remove_song_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Music.album'),
        ),
    ]
