# Generated by Django 4.0 on 2022-01-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='album/thumbnail'),
        ),
    ]
