# Generated by Django 4.0 on 2022-01-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
    ]
