# Generated by Django 4.0 on 2022-01-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_album_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
