# Generated by Django 4.0 on 2022-01-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_album_description_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
