# Generated by Django 4.0 on 2022-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_alter_album_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
