# Generated by Django 4.0 on 2022-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_alter_album_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
