# Generated by Django 4.0 on 2022-01-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_album_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='timestamp',
            new_name='duration',
        ),
    ]
