# Generated by Django 4.0 on 2022-01-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_rename_timestamp_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='description',
        ),
    ]
