# Generated by Django 4.0 on 2022-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0013_remove_song_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='', upload_to='album/songs'),
        ),
    ]
