# Generated by Django 4.0 on 2022-01-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0014_song_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='song_file',
        ),
    ]
