# Generated by Django 3.2.4 on 2021-11-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211025_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=80)),
                ('phNumber', models.CharField(max_length=15)),
                ('userMsg', models.CharField(max_length=500)),
            ],
        ),
    ]
