# Generated by Django 3.2.4 on 2021-11-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='userMsg',
        ),
    ]
