# Generated by Django 3.2.4 on 2021-11-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211109_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('itemsJson', models.CharField(default='', max_length=5000)),
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('zipCode', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
