# Generated by Django 4.0 on 2021-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=500)),
                ('password', models.CharField(default='', max_length=200)),
                ('text_area', models.TextField(default='')),
            ],
        ),
    ]
