# Generated by Django 4.0 on 2021-12-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='text_area',
            new_name='text',
        ),
    ]
