# Generated by Django 4.0.1 on 2022-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=150)),
                ('images', models.ImageField(upload_to='media/graphic_images')),
            ],
        ),
    ]
