# Generated by Django 4.0.1 on 2022-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='images',
            field=models.ImageField(default='', upload_to='page/graphic_images'),
        ),
    ]
