# Generated by Django 4.0.1 on 2022-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_graphic_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='for_text',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphic',
            name='text_color',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphic',
            name='what_text',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
