# Generated by Django 4.0.1 on 2022-02-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_graphic_for_text_graphic_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='text_color',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
