# Generated by Django 4.0.1 on 2022-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_graphic_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='for_whom_category',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
