# Generated by Django 4.0.1 on 2022-02-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_graphic_for_whom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='default_color',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='text_color',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
