# Generated by Django 4.0.1 on 2022-02-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_graphic_default_color_alter_graphic_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
