# Generated by Django 4.0.1 on 2022-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_graphic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='image_color',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
