# Generated by Django 4.0.1 on 2022-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_graphic_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='for_text',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='what_text',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
