# Generated by Django 4.0.1 on 2022-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_graphic_for_text_alter_graphic_what_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyImage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=500)),
                ('image1', models.ImageField(upload_to='many_images/<django.db.models.fields.CharField>/image<django.db.models.fields.AutoField>')),
            ],
        ),
    ]
