# Generated by Django 4.0.1 on 2022-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_manyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyimage',
            name='category',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='manyimage',
            name='image1',
            field=models.ImageField(default='', upload_to='many_images/category/image'),
        ),
    ]
