# Generated by Django 4.0 on 2022-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=999)),
                ('useremail', models.CharField(default='', max_length=999)),
                ('feedback', models.TextField(default='', max_length=1000000)),
            ],
        ),
    ]
